apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-jwt-api
  labels:
    app: simple-jwt-api
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: simple-jwt-api
  template:
    metadata:
      labels:
        app: simple-jwt-api
    spec:
      containers:
      - name: simple-jwt-api
        image: your-docker-repo/simple-jwt-api:latest  # Replace with your actual Docker image
        ports:
        - containerPort: 8080  # Adjust if your app runs on a different port
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        # Add other environment variables as needed
---
apiVersion: v1
kind: Service
metadata:
  name: simple-jwt-api
spec:
  type: LoadBalancer  # This creates an external load balancer
  ports:
    - port: 80        # Port exposed by the service
      targetPort: 8080  # Port on which the container is listening
  selector:
    app: simple-jwt-api  # Match the labels in the Deployment
